name: Build the plugin

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - run: |
          ./ci/download_deps.sh
          ./gradlew build --no-daemon
        name: "Build using Gradle"